spring.application.name=Krishibandhu


spring.datasource.url=jdbc:mysql://localhost:3306/krishibandhu

spring.datasource.username=root
spring.datasource.password=Nitin@2004

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080

weather.api.key=2918a352bd66b8c67d247845671da667
market.api.key=579b464db66ec23bdd000001cea322b18e8f4e9f442a92e7ec4b6591
gemini.api.key=AQ.Ab8RN6Jkca6ufZkrIgdqBM-VwAB7SiP0basWzdO6OfZrbhhD1A